### ISSUE TITLE
Requesting expanded data for a product without expanded data causes empty set results

### ISSUE THREAD

**Issue by jzollerneon** [NEONScience/neon-data-api#11]
http://data.neonscience.org/api/v0/data/DP1.10072.001/TALL/2014-09?package=expanded returns

{
  "status": 200,
  "data": {
    "files": [],
    "productCode": "DP1.10072.001",
    "urls": [],
    "month": "2014-09",
    "siteCode": "TALL"
  }
}

but should probably return the basic data instead.

**Comment by chrlaney** [comment]
I think that this should not return the basic package, as this could be confusing to the end user. Instead, a message could be returned - "An expanded package does not exist for this data product. If you would like the basic package, use the following URL: [correct URL for basic package]".
