### ISSUE TITLE
[enhancement] Provide Resource URLs in Response or Relational Routes

### ISSUE THREAD

**Issue by npnlee85** [NEONScience/neon-data-api#15]
It might be convenient to provide in the response, either routes to additional resources, or provide a way to show relationships between different entities. For instance, as I was perusing the data, I had to find a site Id and product id separately before I could query for data. The /sites/{siteCode} endpoint provides available data products, but maybe it could also return URLs to those resources. Or maybe you could add routes to that end, e.g.:

/sites/{siteCode}/{productCode}/{year-month}

**Comment by jzollerneon** [comment]
The next release (planned for early next week) will add relational routes to the /sites, /products, and /locations endpoints.

/sites will have a new data.dataProducts.availableDataUrls array per site, with links of the format "http://data.neonscience.org:80/api/v0/data/<productCode>/<siteCode>/<year-month>".

/products will have a new data.siteCodes.availableDataUrls array per product, with links of the format "http://data.neonscience.org:80/api/v0/data/<productCode>/<siteCode>/<year-month>".

/locations will have two new url entries: one for the parent location, and one for every child location.  The format will be "http://data.neonscience.org:80/api/v0/locations/<locationName>".

More details will be in the official documentation at [http://data.neonscience.org/data-api](http://data.neonscience.org/data-api) once the release is completed.

Thanks for the feedback, and apologies for taking so long to act on it!
