### ISSUE TITLE
Incomplete product information - productCode: DP1.10072.001

### ISSUE THREAD

**Issue by jwhody** [NEONScience/neon-data-api#17]
API no longer provides information regarding the availability of small mammal box trap data (productCode: DP1.10072.001).

/products/DP1.10072.001 previously included information regarding which sites and months were available for download (info included at least through 07-June-2017).

However, this information has been now been completely removed ("siteCodes": null).
Not sure if this might just be due to an update/change (product status currently active), but noting it just in case.

**Comment by chrlaney** [comment]
We are currently republishing this data product, I believe you should see the information reappear by tomorrow.

**Comment by jwhody** [comment]
Thank you very much for the quick response! I thought it might just be an update to the product, but figured I'd mention it just in case. Again, thanks!

**Comment by chrlaney** [comment]
You're welcome, and thanks for the feedback!

**Comment by chrlaney** [comment]
My apologies - we have run into a bit of a delay and do not anticipate having the republished data available until Monday or Tuesday.
