### ISSUE TITLE
How to find exact locations of data product at a site

### ISSUE THREAD

**Issue by jirikadlec2** [NEONScience/neon-data-api#18]
At a NEON site a data product is often measured by multiple sensors at different locations. When I have a data product, how do I find the locations of the associated sensors / sensor locations?

For example at the site "ABBY" I can get the data product "DP1.00098.001" (Relative humidity)
When I visit one of the availableDataURLs: 
http://data.neonscience.org:80/api/v0/data/DP1.00098.001/ABBY/2016-04
I can see there are multiple data product file names:
- NEON.D16.ABBY.DP1.00098.001.000.040.030.RH_30min.2016-04.basic.20171026T095524Z.csv
- NEON.D16.ABBY.DP1.00098.001.003.000.030.RH_30min.2016-04.basic.20171026T095524Z.csv

The documentation says that the code is: NEON.DOM.SITE.DPL.PRNUM.REV.HOR.VER
where HOR is the index of the sensor in the sensor array and VER is the vertical offset
This means for site ABBY there are two relative humidity sensors, one with HOR=000 and VER=040,
second with HOR = 003 and VER=000.

When I have a data product such as: NEON.D16.ABBY.DP1.00098.001.003.000.030.RH_30min.2016-04.basic.20171026T095524Z.csv how do I find the horizontal position or offset relative to the main station? Is this information available via the NEON API?

Thanks,
Jiri Kadlec

**Comment by chrlaney** [comment]
Hello Jiri (@jirikadlec2),

Thanks for getting in touch with us. Instrumented data published after November of 2017 now include files with sensor positions (the files contain “sensor_positions” in the file name). Unfortunately, the publication of ABBY relative humidity data was interrupted prior to this. You can access the information via the /locations endpoint. 

http://data.neonscience.org/api/v0/locations/ABBY provides a long list of locationChildren, one of which is TOWER102005. 
http://data.neonscience.org/api/v0/locations/TOWER102005 provides the reference lat, lon, and elevation, plus another list of locationChildren. Levels have labels, but no descriptions so it takes some scripting or trial and error to locate the level and sensors of interest. Once you get to the locations that start with "CFGLOC", the locationDescription field will tell you what sensor is there. 

For example:
http://data.neonscience.org/api/v0/locations/LEVEL110985
leads to 
http://data.neonscience.org/api/v0/locations/BOOM110986
and so forth, to individual assemblies.

Single aspirated air temperature assembly, level 4:
http://data.neonscience.org/api/v0/locations/CFGLOC110987.

Relative humidity, level 5 (tower top):
http://data.neonscience.org/api/v0/locations/CFGLOC102032

Relative humidity, soil array position 3:
http://data.neonscience.org/api/v0/locations/CFGLOC102122.

We are working on better methods of presenting and documenting this information in the future.  Thanks for any feedback you care to offer!

**Comment by chrlaney** [comment]
Adding work to development queue to return all levels of location hierarchy in response.
