### ISSUE TITLE
sensor_positions csv file with empty referenceLatitude, referenceLongitude and referenceElevation

### ISSUE THREAD

**Issue by jirikadlec2** [NEONScience/neon-data-api#19]
Hello,
I am not sure if this is a bug, but  some of the sensor_positions.csv files in the downloaded NEON data products have empty referenceLatitude, referenceLongitude and referenceElevation fields.
Does it mean the latitude, longitude and elevation is unknown, or does it mean I should use the latitude, longitude and elevation of the parent site as my reference?

The link to the file is available via the API:
http://data.neonscience.org/api/v0/data/DP1.00002.001/WREF/2018-03
The name of the sensor_positions file with some empty fields is: NEON.D16.WREF.DP1.00002.001.sensor_positions.20180418T161826Z.csv

Best regards,
Jiri Kadlec

**Comment by chrlaney** [comment]
Thank you Jiri @jirikadlec2 for contacting us!

@covesturtevant @MorganEJones - does the sensor location data for WREF needs to be loaded into PDR? Thank you!

**Comment by jirikadlec2** [comment]
Apologies for not responding earlier - I can confirm that the sensor position data for site WREF are there.
