### ISSUE TITLE
child locations

### ISSUE THREAD

**Issue by cklunch** [NEONScience/neon-data-api#4]
A /location call returns information about a location and a list of its child locations, but doesn't go any deeper than the child level (no grandchild, great-grandchild locations). It would be great to be able to pull the entire location hierarchy below (or above?) a given location in a single call.

**Comment by chrlaney** [comment]
@cklunch Is this close to what you're looking for? http://data.neonscience.org/api/v0/locations/STER_009.basePlot.mfb
