### ISSUE TITLE
geodeticDatum

### ISSUE THREAD

**Issue by scelmendorf** [NEONScience/neon-data-api#6]
Certainly could be user-error, but I didn't see geodeticDatum exposed via the locations API call.  I know it's WGS84, but I think not everyone will?

**Comment by sckott** [comment]
agree, would be nice if that was explicit

**Comment by scelmendorf** [comment]
@jzollerneon the datum, along with a few additional pieces of info (county, stateProvince, country) should now be accessible to you.  When you roll back around to this, can you add those to the api?

**Comment by jzollerneon** [comment]
@scelmendorf I've added a user story for this, and notified @chrlaney.  We'll get it prioritized and in place.  Thanks!

**Comment by chrlaney** [comment]
These fields in are in the locationProperties field, e.g., {"locationPropertyName":"Value for Geodetic datum","locationPropertyValue":"WGS84"},{"locationPropertyName":"Value for State province","locationPropertyValue":"WA"}
